name: quanlyhoctap
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  fl_chart: 0.69.2
  flutter_form_builder: ^9.5.0
  flutter_secure_storage: ^9.2.2
  form_builder_validators: ^11.0.0
  go_router: ^14.3.0
  http: ^1.2.2
  provider: ^6.1.2
  loading_animation_widget: ^1.3.0
  stomp_dart_client: ^2.1.0
  dio: ^5.7.0
  form_builder_file_picker: ^4.2.0
  flutter_localizations:
    sdk: flutter
  intl: ^0.19.0
  lazy_load_scrollview: ^1.3.0
  collection: ^1.18.0
  sidebarx: ^0.17.1
  calendar_slider: ^0.0.4
  file_picker: 8.1.4
  mqtt_client: ^9.7.0
  # ndialog: ^4.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/certs/DeviceCertificate.crt
    - assets/certs/PrivateKey.key
    - assets/certs/AmazonRootCA1.pem
